---
dgi_migrate_big_set_overrides.settings:
  type: config_object
  label: 'Override settings'
  mapping:
    overrides:
      type: sequence
      label: 'The overrides to set.'
      sequence:
        type: dgi_migrate_big_set_overrides.settings.override
        label: 'Override'

dgi_migrate_big_set_overrides.settings.override:
  type: mapping
  label: 'Targeted override info.'
  mapping:
    config:
      type: string
      label: 'The name of the config in which to set the override.'
    parents:
      type: sequence
      label: 'The parent elements to traverse to find where to set the override value.'
      sequence:
        type: ignore
        label: 'Parent element'
    value:
      type: ignore
      label: 'The value to set.'
